export enum CustomErrorCode {
    // Authentication
    AUTH_MISSING = 'TB_AUTH_100',
    AUTH_INVALID = 'TB_AUTH_101',
    AUTH_EXPIRED = 'TB_AUTH_102',

    AUTH_BLOCKED = 'TB_AUTH_103',
    SESSION_EXPIRED = 'TB_AUTH_104',

    // Permission
    ACCESS_DENIED = 'TB_PERM_200',
    ACTION_NOT_ALLOWED = 'TB_PERM_201',


    // Validation
    INVALID_INPUT = 'TB_VAL_300',
    FIELD_FORMAT_INVALID = 'TB_VAL_301',
    VALIDATION_ERROR = 'TB_VAL_302',
    DUPLICATE_RESOURCE = 'TB_VAL_303',

    // Resource
    RESOURCE_NOT_FOUND = 'TB_RES_400',
    RESOURCE_EXISTS = 'TB_RES_401',
    RESOURCE_STATE_INVALID = 'TB_RES_402',

    // Bad request
    BAD_REQUEST = 'TB_BR_403',

    // System
    INTERNAL_ERROR = 'TB_SYS_600',
    UNSUPPORTED_ACTION = 'TB_SYS_602',

    // Limits
    RATE_LIMIT_EXCEEDED = 'TB_LIM_700',
    QUOTA_EXCEEDED = 'TB_LIM_701',
    TOO_MANY_ATTEMPTS = 'TB_LIM_702',

    // Payments
    PAYMENT_FAILED = 'TB_PAY_800',
    PAYMENT_METHOD_UNSUPPORTED = 'TB_PAY_801',
    REFUND_FAILED = 'TB_PAY_802',
    INTERNAL_SERVER_ERROR = 'TN_ISE_901',

    //Tenant Error codes
    TENANT_PENDING_APPROVAL = 'TENANT_PENDING_APPROVAL',
    TENANT_REJECTED='TENANT_REJECTED',
    TENANT_SUSPENDED='TENANT_SUSPENDED',
    TENANT_UNAVAILABLE='TENANT_UNAVAILABLE',

}